name: 'follow_circle'
version: 0.4.6
description: Example of Pub 'n Sub version DSA model
author: Matthew Butler <butler.matthew@gmail.com>
homepage: http://butlermatt.me

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  dslink:
    git: git://github.com/IOT-DSA/sdk-dslink-dart.git

transformers:
- dart_to_js_script_rewriter